// lib/ollama.ts

import fetch from 'node-fetch';

/**
 * Ollama API client for sending requests and handling responses.
 */
export async function generateText(prompt: string, model: string = "qwen2.5-coder:7b"): Promise<string> {
  try {
    const response = await fetch('http://localhost:11434/api/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt,
        model,
        stream: false,
      }),
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();
    return data.response;
  } catch (error) {
    console.error('Error generating text with Ollama API:', error);
    return 'Fallback text generated by the system.';
  }
}